version: "3.3"

services:

  locust:
    build:
      context: .
      dockerfile: Dockerfile
    image: recommendations
    command: "locust --web-host=0.0.0.0"
    depends_on:
      - recommendations_client
    network_mode: host
    volumes:
      - ./recommendations:/service/recommendations
    environment:
      - RECOMMENDATIONS_CLIENT_HOST=${RECOMMENDATIONS_CLIENT_HOST}
