version: "3.3"

services:

  recommendations_grpc:
    build:
      context: .
      dockerfile: Dockerfile
    image: recommendations
    command: python server.py
    network_mode: host
    volumes:
      - ./recommendations:/service/recommendations

  recommendations_rest:
    build:
      context: .
      dockerfile: Dockerfile
    image: recommendations
    command: python server_rest.py
    network_mode: host
    volumes:
      - ./recommendations:/service/recommendations

  recommendations_client:
    build:
      context: .
      dockerfile: Dockerfile
    image: recommendations
    command: python client.py
    network_mode: host
    depends_on:
      - recommendations_grpc
      - recommendations_rest
    volumes:
      - ./recommendations:/service/recommendations
    environment:
      - RECOMMENDATIONS_HOST=127.0.0.1

  locust:
    build:
      context: .
      dockerfile: Dockerfile
    image: recommendations
    command: "locust --users 10 --spawn-rate 2"
    depends_on:
      - recommendations_client
    network_mode: host
    volumes:
      - ./recommendations:/service/recommendations
    environment:
      - RECOMMENDATIONS_HOST=127.0.0.1
