version: "3.3"

services:

  recommendations_grpc:
    build:
      context: .
      dockerfile: Dockerfile
    image: recommendations
    command: python server.py
    network_mode: host
    volumes:
      - ./recommendations:/service/recommendations

  recommendations_rest:
    build:
      context: .
      dockerfile: Dockerfile
    image: recommendations
    command: python server_rest.py
    network_mode: host
    volumes:
      - ./recommendations:/service/recommendations
