# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\x12\x0frecommendations\"/\n\x12\x42ookRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"S\n\x13\x42ookRecommendations\x12<\n\x0frecommendations\x18\x01 \x03(\x0b\x32#.recommendations.BookRecommendation\"=\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\x32\xdd\x01\n\x0fRecommendations\x12\x63\n\x13get_recommend_books\x12&.recommendations.RecommendationRequest\x1a$.recommendations.BookRecommendations\x12\x65\n\x14get_recommend_stream\x12&.recommendations.RecommendationRequest\x1a#.recommendations.BookRecommendation0\x01\x62\x06proto3')



_BOOKRECOMMENDATION = DESCRIPTOR.message_types_by_name['BookRecommendation']
_BOOKRECOMMENDATIONS = DESCRIPTOR.message_types_by_name['BookRecommendations']
_RECOMMENDATIONREQUEST = DESCRIPTOR.message_types_by_name['RecommendationRequest']
BookRecommendation = _reflection.GeneratedProtocolMessageType('BookRecommendation', (_message.Message,), {
  'DESCRIPTOR' : _BOOKRECOMMENDATION,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:recommendations.BookRecommendation)
  })
_sym_db.RegisterMessage(BookRecommendation)

BookRecommendations = _reflection.GeneratedProtocolMessageType('BookRecommendations', (_message.Message,), {
  'DESCRIPTOR' : _BOOKRECOMMENDATIONS,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:recommendations.BookRecommendations)
  })
_sym_db.RegisterMessage(BookRecommendations)

RecommendationRequest = _reflection.GeneratedProtocolMessageType('RecommendationRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONREQUEST,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:recommendations.RecommendationRequest)
  })
_sym_db.RegisterMessage(RecommendationRequest)

_RECOMMENDATIONS = DESCRIPTOR.services_by_name['Recommendations']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKRECOMMENDATION._serialized_start=42
  _BOOKRECOMMENDATION._serialized_end=89
  _BOOKRECOMMENDATIONS._serialized_start=91
  _BOOKRECOMMENDATIONS._serialized_end=174
  _RECOMMENDATIONREQUEST._serialized_start=176
  _RECOMMENDATIONREQUEST._serialized_end=237
  _RECOMMENDATIONS._serialized_start=240
  _RECOMMENDATIONS._serialized_end=461
# @@protoc_insertion_point(module_scope)
